### ISSUE TITLE
error: getting cc1 / gcc errors

### ISSUE THREAD

**Issue by NickTheOnlyNeko** [KanuX-14/rtl8188eus#1]
i have Linux Arch with Downgraded Linux LTS kernel down to 5.10.xx

cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
cc1: error: incompatible gcc/plugin versions
cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
  CC [M]  /home/nick/rtl8188eus/core/rtw_ioctl_set.o
cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so

**Comment by KanuX-14** [comment]
Might have to take a look on that.
Apart from this, is there any other log returning a error within the code?

**Comment by NickTheNeko2002** [comment]
> Might have to take a look on that. Apart from this, is there any other log returning a error within the code?

nope, not really tho i think i may have broken Linux Arch by using an older Kernel version

**Comment by KanuX-14** [comment]
> i think i may have broken Linux Arch by using an older Kernel version
Which GCC version are you using?

**Comment by NickTheNeko2002** [comment]
> > i think i may have broken Linux Arch by using an older Kernel version
> 
> Which GCC version are you using?

the newest/latest version of of gcc, i tried downgrading it but it didn't want to downgrade
(i used `sudo downgrade gcc` but all that happened was nothing except for it to tell me that it can't downgrade gcc)

**Comment by KanuX-14** [comment]
I guess this was a GCC error by the result of the attempt of downgrade. If you want to strict a GCC version, you can use `--std=cXX`.

**Comment by KanuX-14** [comment]
Honestly, I have no idea about what this error could be related to the repository itself.<br>
Might be a GCC error back then.

Closing as not knowing the resolution...

**Comment by KanuX-14** [comment]
After a little bit o search, it seems that the GCC environment has plugins:
> cc1: error: incompatible gcc/plugin versions
It will be marked as fixed.
