### ISSUE TITLE
Unable to compile! Please read! [Issue]

### ISSUE THREAD

**Issue by Gamer100Dev** [KanuX-14/rtl8188eus#12]
**Issue**
[gamer@Linux rtl8188eus]$ git clone --depth 1 https://gitlab.com/KanuX/rtl8188eus.git
cd rtl8188eus/
make -j$(nproc)
su -c "make install clean"
su -c "modprobe 8188eu"
Cloning into 'rtl8188eus'...
remote: Enumerating objects: 540, done.
remote: Counting objects: 100% (540/540), done.
remote: Compressing objects: 100% (390/390), done.
remote: Total 540 (delta 151), reused 487 (delta 144), pack-reused 0
Receiving objects: 100% (540/540), 2.59 MiB | 8.29 MiB/s, done.
Resolving deltas: 100% (151/151), done.
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.7.2-arch1-1/build M=/home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus  modules
make[1]: Entering directory '/usr/lib/modules/6.7.2-arch1-1/build'
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_cmd.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_security.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_debug.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_io.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_ioctl_query.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_ioctl_set.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_ieee80211.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_mlme.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_mlme_ext.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_mi.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_wlan_util.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_vht.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_pwrctrl.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_rf.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_recv.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_sta_mgt.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_ap.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/mesh/rtw_mesh.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_xmit.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_p2p.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_rson.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_tdls.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_br_ext.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_iol.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_sreset.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_btcoex_wifionly.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_btcoex.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_beamforming.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_odm.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_rm.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/rtw_rm_fsm.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/core/efuse/rtw_efuse.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/osdep_service.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/os_intfs.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/usb_intf.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/usb_ops_linux.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/ioctl_linux.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/xmit_linux.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/mlme_linux.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/recv_linux.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/wifi_regd.o
/home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/ioctl_cfg80211.c:9416:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Werror=incompatible-pointer-types]
 9416 |         .change_beacon = cfg80211_rtw_change_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/ioctl_cfg80211.c:9416:26: note: (near initialization for ‘rtw_cfg80211_ops.change_beacon’)
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/rtw_android.o
  CC [M]  /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/rtw_proc.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus/os_dep/linux/ioctl_cfg80211.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/lib/modules/6.7.2-arch1-1/build/Makefile:1911: /home/gamer/.local/share/Trash/files/rtl8188eus/rtl8188eus/rtl8188eus] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.7.2-arch1-1/build'
make: *** [Makefile:2058: modules] Error 2

Sorry if it is the wrong formatting.

**Comment by KanuX-14** [comment]
Sorry. I fixed this since the start of the year, but it was during kernel 6.7-rc4 development. Then I forgot to update it lately.

There is an issue on kernel 6.8 too, have got to take a look on that.
