### ISSUE TITLE
error: make install error under Android

### ISSUE THREAD

**Issue by lucky-zwx** [KanuX-14/rtl8188eus#4]
![Screenshot_20221101_124626](https://user-images.githubusercontent.com/34543176/199161066-671a0c28-d6a4-4432-a314-3d6e0fe8ebde.jpg)
I use kali nethunter on Nexus 6p.

**Comment by KanuX-14** [comment]
I looked up into the files and the kernel version is grabbed by doing the `uname -r` command.<br>
Could you post the output of the command, please? It seems like your installation grabbed your actual source kernel.

**Comment by suspense1234** [comment]
┌──(sus㉿Pheonix)-[~/Desktop/rtl8188eus]
└─$ make && make install clean
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.1.0-kali7-amd64/build M=/home/sus/Desktop/rtl8188eus  modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-kali7-amd64'
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-kali7-amd64'
install -p -m 644 8188eu.ko  /lib/modules/6.1.0-kali7-amd64/kernel/drivers/net/wireless/
install: cannot remove '/lib/modules/6.1.0-kali7-amd64/kernel/drivers/net/wireless/8188eu.ko': Permission denied
make: *** [Makefile:2064: install] Error 1

**Comment by suspense1234** [comment]
Anybody can help?

**Comment by KanuX-14** [comment]
@suspense1234

> $ make && make install clean

$ means you are normal user. The installer runs as root user #.<br>
Depending on your environment, you might use `sudo`, `doas`, or the default `su`.

**Comment by KanuX-14** [comment]
There is nothing to be fixed since this error has to do with Android's kernel and not the virtual machine's kernel.

Building a driver in Android kernel is possible, but only if the full kernel is installed.
