### ISSUE TITLE
sudo rmmod r8188eu not workin

### ISSUE THREAD

**Issue by g30rg101** [KanuX-14/rtl8188eus#5]
![image](https://user-images.githubusercontent.com/116904432/199351520-adc00aa1-e68b-4b31-9675-0520d0816eb0.png)

**Comment by KanuX-14** [comment]
Is the device connected? Which model is it?

**Comment by g30rg101** [comment]
TP-LINK TL-WN723N v3
I'm using virtualbox, letting you know, maybe I'm missing something, if I should do something with the settings there?

**Comment by KanuX-14** [comment]
Could be a problem with the virtualization. Did you enabled the USB port on the settings?

**Comment by PalPat1ne** [comment]
I have the same problem, but I'm not using virtualbox but wmwire
![image](https://user-images.githubusercontent.com/64207546/199850713-1aa9e910-a9f2-4f7b-bb8b-1b57dd7c0994.png)
![image](https://user-images.githubusercontent.com/64207546/199850777-c014d8f6-ee5e-4a78-b6b1-ae371066212d.png)
![image](https://user-images.githubusercontent.com/64207546/199850833-63ac039b-95a7-4a55-bf2b-662641bb17cb.png)
