### ISSUE TITLE
adapter not working

### ISSUE THREAD

**Issue by PalPat1ne** [KanuX-14/rtl8188eus#6]
I restarted the system, checked the USB connection in the virtual machine, but it does not appear as a network interface
![image](https://user-images.githubusercontent.com/64207546/199853356-3271f17b-d6a2-4f2b-b6a7-15eae5f2c9c1.png)
![image](https://user-images.githubusercontent.com/64207546/199853394-242f5374-f717-43e6-816a-c3f1677d07cc.png)

**Comment by PalPat1ne** [comment]
it turns out I have another error
![image](https://user-images.githubusercontent.com/64207546/199855242-ca1e13b6-0b62-4ee7-8c17-ca53e92d2f01.png)

**Comment by KanuX-14** [comment]
You must **need** the kernel headers installed in order to build **any** customised module.

**Comment by PalPat1ne** [comment]
Thank you very much, I've been struggling with this for 2 weeks, thanks again

**Comment by KanuX-14** [comment]
You can close as resolved as your wish.
